services: 
  go-server: 
    container_name: go-server
    image: prometheusdemo/go-server
    build: 
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 8081:80
    networks:
      - backend-services
networks:
  backend-services:
    external: true